# Generated by Django 5.2.6 on 2025-09-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_country',
            field=models.CharField(default='UK', max_length=40),
            preserve_default=False,
        ),
    ]
