# Generated by Django 3.2.25 on 2025-09-06 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('role', models.CharField(choices=[('author', 'Author'), ('illustrator', 'Illustrator')], max_length=30)),
                ('about', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('age', 'Age Group'), ('genre', 'Genre')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cover_type', models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback')], max_length=10)),
                ('illustration_type', models.CharField(choices=[('none', 'No illustrations'), ('bw', 'Black & White'), ('color', 'Full Colour')], max_length=10)),
                ('language', models.CharField(choices=[('eng', 'English'), ('ukr', 'Ukrainian')], default='ukr', max_length=30)),
                ('pages', models.PositiveIntegerField()),
                ('dimensions', models.CharField(blank=True, max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('authors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'author'}, related_name='authored_books', to='books.BookContributor')),
                ('categories', models.ManyToManyField(related_name='books', to='books.Category')),
                ('illustrators', models.ManyToManyField(blank=True, limit_choices_to={'role': 'illustrator'}, related_name='illustrated_books', to='books.BookContributor')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.publisher')),
            ],
        ),
    ]
