# Generated by Django 3.2.25 on 2025-09-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='screen_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
