# Generated by Django 3.2.25 on 2025-09-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20250918_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='age_group',
            field=models.CharField(blank=True, choices=[('children', 'Children'), ('teens', 'Teens'), ('adults', 'Adults')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-fiction'), ('learning', 'Learning'), ('hobby', 'Hobby'), ('specials', 'Gifts')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('genre', 'age_group')},
        ),
    ]
