# Generated by Django 3.2.25 on 2025-09-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20250918_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='age_groups',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='age_group',
            field=models.CharField(blank=True, choices=[('children', 'Children'), ('teens', 'Teens'), ('adults', 'Adults'), ('all', 'All')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-fiction'), ('learning', 'Learning'), ('hobby', 'Hobby'), ('specials', 'Specials')], max_length=50, null=True),
        ),
    ]
