# Generated by Django 3.2.25 on 2025-09-18 11:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20250918_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='age_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('children', 'Children'), ('teens', 'Teens'), ('adults', 'Adults'), ('all', 'All')], max_length=25, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
