# Generated by Django 3.2.25 on 2025-09-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20250918_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this category from public view'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'genre__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='books.category'),
        ),
    ]
