# Generated by Django 3.2.25 on 2025-09-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20250918_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='genre',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'subcategory__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='books.category'),
        ),
    ]
